global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "hadoop"
    static_configs:
      - targets:
          - "namenode:9870"
          - "datanode1:9864"
          - "datanode2:9864"

  - job_name: "spark"
    static_configs:
      - targets: ["spark-master:8080"]

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch:9200"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]
